Experiment_name: VSL_v1.1.1

# feeder
dataset: VSL # [WLASL100, WLASL300, WLASL1000, WLASL2000, SLR500, AUTSL, WLASL300_mediapipe, WLASL100_mediapipe, VSL]
feeder: feeders.feeder.Feeder

test_feeder_args:
  random_mirror: False
  normalization: True
  lap_pe: False
  debug: False
  random_choose: True
  window_size: 120  # 100 for AUTSL, 120 for others
  bone_stream: False # True or False
  motion_stream: True # True or False

# model
model: model.fstgan.Model
model_args:
  num_class: 100   # 100 for WLASL100, 300 for WLASL300, 1000 for WLASL1000, 2000 for WLASL2000, 226 for AUTSL, 500 for SLR500, 100 for VSL
  num_point: 27
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'
  inner_dim: 64
  depth: 4
  drop_layers: 2


# testing
device: [0]
phase: test
weights: work_dir/VSL_v1.1.1/save_models/best_model.pt
test_batch_size: 24
num_worker: 4
wandb: False